"""Dashboard renderer — generates vault/Dashboard.md from orchestrator state.

Pure functions for rendering, with atomic file writing for safe Obsidian updates.
"""

from __future__ import annotations

import logging
import os
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from backend.orchestrator.watchdog import WatcherInfo

logger = logging.getLogger(__name__)


@dataclass
class DashboardState:
    """Snapshot of the orchestrator's current state for dashboard rendering."""

    watchers: list[WatcherInfo] = field(default_factory=list)
    vault_counts: dict[str, int] = field(default_factory=dict)
    dev_mode: bool = True
    last_update: str = ""
    uptime_seconds: int = 0
    errors: list[str] = field(default_factory=list)


def count_vault_files(vault_path: str | Path) -> dict[str, int]:
    """Count .md files in each vault subfolder.

    Returns:
        Dict mapping folder names to file counts.
    """
    vault = Path(vault_path)
    folders = [
        "Inbox",
        "Needs_Action",
        "Plans",
        "Pending_Approval",
        "Approved",
        "Rejected",
        "Done",
    ]

    counts: dict[str, int] = {}
    for folder in folders:
        folder_path = vault / folder
        if folder_path.exists():
            counts[folder] = len(list(folder_path.glob("*.md")))
        else:
            counts[folder] = 0

    return counts


def render_dashboard(state: DashboardState) -> str:
    """Pure function: render DashboardState to a markdown string.

    Args:
        state: Current orchestrator state snapshot.

    Returns:
        Complete markdown content for Dashboard.md.
    """
    lines: list[str] = []

    # Header
    mode_badge = "DEV MODE" if state.dev_mode else "PRODUCTION"
    lines.append(f"# AI Employee Dashboard [{mode_badge}]")
    lines.append("")
    lines.append(f"**Last Updated**: {state.last_update}")
    lines.append(f"**Uptime**: {_format_uptime(state.uptime_seconds)}")
    lines.append("")

    # Watcher Status Table
    lines.append("## Watcher Status")
    lines.append("")
    if state.watchers:
        lines.append("| Watcher | Status | Restarts | Last Error | Started |")
        lines.append("|---------|--------|----------|------------|---------|")
        for w in state.watchers:
            status_icon = _status_icon(w.status)
            error = (w.last_error or "—")[:60]
            started = w.started_at or "—"
            lines.append(
                f"| {w.name} | {status_icon} {w.status} | {w.restart_count} | {error} | {started} |"
            )
    else:
        lines.append("*No watchers configured.*")
    lines.append("")

    # Vault Folder Counts
    lines.append("## Vault Status")
    lines.append("")
    lines.append("| Folder | Files |")
    lines.append("|--------|-------|")
    for folder, count in state.vault_counts.items():
        lines.append(f"| {folder} | {count} |")
    lines.append("")

    # Errors
    if state.errors:
        lines.append("## Recent Errors")
        lines.append("")
        for err in state.errors:
            lines.append(f"- {err}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Auto-generated by AI Employee Orchestrator. Do not edit manually.*")

    return "\n".join(lines)


async def write_dashboard(vault_path: str | Path, content: str) -> None:
    """Write dashboard content atomically via temp file + os.replace.

    This ensures Obsidian never reads a partially-written file.
    """
    vault = Path(vault_path)
    dashboard_path = vault / "Dashboard.md"

    # Write to temp file in same directory (required for atomic rename)
    fd, tmp_path = tempfile.mkstemp(
        dir=str(vault),
        prefix=".dashboard-",
        suffix=".tmp",
    )
    try:
        os.write(fd, content.encode("utf-8"))
        os.close(fd)
        os.replace(tmp_path, str(dashboard_path))
        logger.debug("Dashboard updated: %s", dashboard_path)
    except Exception:
        os.close(fd) if not os.get_inheritable(fd) else None  # noqa: B018
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise


def _format_uptime(seconds: int) -> str:
    """Format uptime seconds to human-readable string."""
    if seconds < 60:
        return f"{seconds}s"
    if seconds < 3600:
        return f"{seconds // 60}m {seconds % 60}s"
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    return f"{hours}h {minutes}m"


def _status_icon(status: str) -> str:
    """Return an icon for the watcher status."""
    icons = {
        "running": "🟢",
        "stopped": "⚪",
        "error": "🟡",
        "failed": "🔴",
        "pending": "⏳",
    }
    return icons.get(status, "❓")
