"""Report formatter — converts BriefingData into the canonical Markdown briefing.

Pure function: BriefingData → str. No I/O. All sections always present,
even with empty/unavailable data (zero-state messages used).

The canonical template is defined in specs/007-ceo-briefing/spec.md.
"""

from __future__ import annotations

from backend.briefing import BriefingData


class ReportFormatter:
    """Formats a BriefingData object into the canonical CEO Briefing Markdown."""

    @staticmethod
    def format(data: BriefingData) -> str:
        """Convert BriefingData to the complete briefing Markdown string.

        Args:
            data: Fully populated BriefingData object.

        Returns:
            Complete Markdown string including YAML frontmatter and all 7 sections.
        """
        parts = [
            ReportFormatter._format_frontmatter(data),
            ReportFormatter._format_header(data),
            ReportFormatter._format_executive_summary(data),
            ReportFormatter._format_financial(data),
            ReportFormatter._format_completed_tasks(data),
            ReportFormatter._format_pending_items(data),
            ReportFormatter._format_communication(data),
            ReportFormatter._format_bottlenecks(data),
            ReportFormatter._format_suggestions(data),
            "\n---\n*Generated by AI Employee v1.0*\n",
        ]
        return "\n".join(parts)

    # ── Frontmatter ──────────────────────────────────────────────────────────

    @staticmethod
    def _format_frontmatter(data: BriefingData) -> str:
        sources = ["vault_done", "vault_logs", "vault_needs_action"]
        if data.financial is not None:
            sources.insert(0, "odoo")
        if data.business_goals is not None:
            sources.append("business_goals")

        generated_str = data.generated_at.strftime("%Y-%m-%dT%H:%M:%SZ")
        period_str = f"{data.period_start.isoformat()} to {data.period_end.isoformat()}"
        period_days = (data.period_end - data.period_start).days + 1
        sources_yaml = "[" + ", ".join(sources) + "]"

        return (
            "---\n"
            f"generated: \"{generated_str}\"\n"
            f"period: \"{period_str}\"\n"
            f"period_start: \"{data.period_start.isoformat()}\"\n"
            f"period_end: \"{data.period_end.isoformat()}\"\n"
            f"period_days: {period_days}\n"
            f"type: ceo_briefing\n"
            f"sources: {sources_yaml}\n"
            f"dev_mode: {'true' if data.dev_mode else 'false'}\n"
            "---"
        )

    # ── Header ───────────────────────────────────────────────────────────────

    @staticmethod
    def _format_header(data: BriefingData) -> str:
        lines = []
        if data.dev_mode:
            lines.append("> ⚠️ DEV MODE — Data is simulated. Do not use for financial decisions.\n")
        lines.append("# Monday Morning CEO Briefing")
        lines.append(
            f"**Period**: {data.period_start.isoformat()} to {data.period_end.isoformat()} "
            f"({(data.period_end - data.period_start).days + 1} days)"
        )
        return "\n".join(lines)

    # ── Executive Summary ────────────────────────────────────────────────────

    @staticmethod
    def _format_executive_summary(data: BriefingData) -> str:
        lines = ["## Executive Summary\n"]

        # Build summary sentences
        task_count = len(data.completed_tasks)
        pending_count = len(data.pending_items)
        period_days = (data.period_end - data.period_start).days + 1

        if data.financial:
            fin = data.financial
            trend_emoji = {"Ahead": "🟢", "On track": "🟡", "Behind": "🔴"}.get(fin.trend, "⚪")
            rev_line = (
                f"Revenue this period: **{fin.currency} {fin.weekly_revenue:,.2f}** "
                f"| MTD: **{fin.currency} {fin.mtd_revenue:,.2f}**"
            )
            if fin.mtd_pct_of_target is not None:
                rev_line += f" ({fin.mtd_pct_of_target:.0f}% of monthly target)"
            rev_line += f" | Trend: {trend_emoji} **{fin.trend}**"
            lines.append(rev_line)
        elif data.financial_error:
            lines.append(f"Financial data unavailable: {data.financial_error}")

        lines.append(
            f"{task_count} task(s) completed this period. "
            f"{pending_count} item(s) pending human action."
        )

        if data.business_goals and data.business_goals.monthly_revenue_target:
            lines.append(
                f"Monthly revenue target: "
                f"{data.business_goals.key_results[0].target if data.business_goals.key_results else 'Set'}"
                " — see Revenue & Financial Health for details."
            )
        elif data.business_goals is None:
            lines.append(
                "Business goals not configured — add `vault/Business_Goals.md` to enable KPI tracking."
            )

        if data.bottlenecks:
            lines.append(
                f"⚠️ {len(data.bottlenecks)} bottleneck(s) detected — see Bottlenecks & Delays."
            )

        return "\n".join(lines)

    # ── Financial ────────────────────────────────────────────────────────────

    @staticmethod
    def _format_financial(data: BriefingData) -> str:
        lines = ["## Revenue & Financial Health\n"]

        if data.financial is None:
            lines.append("> ⚠️ Odoo unavailable — financial data could not be retrieved.")
            if data.financial_error:
                lines.append(f"> Error: {data.financial_error}")
            lines.append("> All other sections reflect current vault data.")
            return "\n".join(lines)

        fin = data.financial
        curr = fin.currency

        # Target line
        target_str = ""
        if fin.monthly_target is not None:
            target_str = f" of {curr} {fin.monthly_target:,.2f} monthly target"
        mtd_pct_str = ""
        if fin.mtd_pct_of_target is not None:
            mtd_pct_str = f" ({fin.mtd_pct_of_target:.0f}%{target_str})"

        lines.append(f"- **This Week Revenue**: {curr} {fin.weekly_revenue:,.2f}")
        lines.append(f"- **MTD Revenue**: {curr} {fin.mtd_revenue:,.2f}{mtd_pct_str}")
        lines.append(
            f"- **Outstanding Invoices**: {fin.outstanding_invoices_count} invoice(s) "
            f"({curr} {fin.outstanding_invoices_total:,.2f} total)"
        )
        lines.append(
            f"- **Recent Payments Received**: {fin.payments_received_count} payment(s) "
            f"({curr} {fin.payments_received_total:,.2f})"
        )
        lines.append(f"- **Cash Position**: {curr} {fin.bank_balance:,.2f} (bank balance)")
        lines.append(f"- **Trend**: {fin.trend}")

        return "\n".join(lines)

    # ── Completed Tasks ──────────────────────────────────────────────────────

    @staticmethod
    def _format_completed_tasks(data: BriefingData) -> str:
        lines = ["## Completed Tasks This Week\n"]

        if not data.completed_tasks:
            lines.append("*No tasks completed in this period.*")
            return "\n".join(lines)

        for task in data.completed_tasks:
            lines.append(f"- [x] {task.title} — {task.completed_date}")

        return "\n".join(lines)

    # ── Pending Items ────────────────────────────────────────────────────────

    @staticmethod
    def _format_pending_items(data: BriefingData) -> str:
        lines = ["## Pending Items\n"]

        if not data.pending_items:
            lines.append("*No pending items.*")
            return "\n".join(lines)

        for item in data.pending_items:
            age_str = f"waiting {item.age_days} day(s)"
            folder = item.vault_folder
            priority = item.priority
            lines.append(f"- [ ] **[{priority.upper()}]** {item.title} — {age_str} ({folder})")

        return "\n".join(lines)

    # ── Communication Summary ────────────────────────────────────────────────

    @staticmethod
    def _format_communication(data: BriefingData) -> str:
        lines = ["## Communication Summary\n"]
        comm = data.communication

        lines.append(f"- **Emails processed**: {comm.emails_processed}")
        lines.append(f"- **WhatsApp messages**: {comm.whatsapp_flagged} flagged")
        lines.append(f"- **LinkedIn messages**: {comm.linkedin_flagged} flagged")
        lines.append(f"- **Social media posts**: {comm.social_posts_published} published this week")
        lines.append(f"- **Total actions logged**: {comm.total_actions}")

        return "\n".join(lines)

    # ── Bottlenecks ──────────────────────────────────────────────────────────

    @staticmethod
    def _format_bottlenecks(data: BriefingData) -> str:
        lines = ["## Bottlenecks & Delays\n"]

        if not data.bottlenecks:
            lines.append("*No bottlenecks detected this period.*")
            return "\n".join(lines)

        lines.append("| Item | Reason | Age (days) |")
        lines.append("|------|--------|------------|")

        for b in data.bottlenecks:
            age = str(b.age_days) if b.age_days is not None else "—"
            reason = b.reason.replace("|", "\\|")  # escape pipes in table
            item = b.item.replace("|", "\\|")
            lines.append(f"| {item} | {reason} | {age} |")

        return "\n".join(lines)

    # ── Proactive Suggestions ────────────────────────────────────────────────

    @staticmethod
    def _format_suggestions(data: BriefingData) -> str:
        lines = ["## Proactive Suggestions\n"]

        if not data.suggestions:
            lines.append("*No suggestions at this time.*")
            return "\n".join(lines)

        # Group by inferred category (simple keyword matching)
        cost_suggestions = [s for s in data.suggestions if any(
            kw in s.lower() for kw in ("invoice", "payment", "revenue", "target", "cost")
        )]
        deadline_suggestions = [s for s in data.suggestions if any(
            kw in s.lower() for kw in ("deadline", "milestone", "upcoming")
        )]
        other_suggestions = [
            s for s in data.suggestions
            if s not in cost_suggestions and s not in deadline_suggestions
        ]

        if cost_suggestions:
            lines.append("### Cost Optimization\n")
            for s in cost_suggestions:
                lines.append(f"- {s}")

        if deadline_suggestions:
            lines.append("\n### Upcoming Deadlines\n")
            for s in deadline_suggestions:
                lines.append(f"- {s}")

        if other_suggestions:
            lines.append("\n### Recommendations\n")
            for s in other_suggestions:
                lines.append(f"- {s}")

        return "\n".join(lines)
